on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Create zip
        id: zip
        run: |
          TAG="${{ github.event.release.tag_name }}"
          # タグが v1.0/resource のような形式を想定している場合
          MAJOR=$(echo $TAG | cut -d'/' -f1)
          MINOR=$(echo $TAG | cut -d'/' -f2)
          FILENAME="${MAJOR}_Japanese-Potion_${MINOR}.zip"
          
          zip -r "${FILENAME}" assets/ pack.mcmeta
          
          # 出力値をセット
          echo "zip_file=${FILENAME}" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip.outputs.zip_file }}
          fail_on_unmatched_files: true
